# Generated by Django 3.2.5 on 2022-09-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mileage', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=500)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autos.make')),
            ],
        ),
    ]
