# Generated by Django 3.2.5 on 2022-09-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220911_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='pic',
            new_name='picture',
        ),
    ]
